name: Test

on:
  pull_request:
    branches: [main, dev]

env:
  SPEECH_REGION: ${{ secrets.SPEECH_REGION }}
  SPEECH_KEY: ${{ secrets.SPEECH_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: "Install requirements"
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg
        
    - name: "Checkout the repository"
      uses: actions/checkout@v5

    - name: "Set up Python"
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        prune-cache: false

    - name: "Test"
      run: uv run pytest
